### ISSUE TITLE
ENOENT, no such file or directory '/var/run/docker.sock'

### ISSUE THREAD

**Issue by sachaudh** [djedi23/meteor-docker#1]
I get this error when I git clone the repo and run it on my machine. How can I fix this?

**Comment by djedi23** [comment]
Good point.
I'm preparing a fix.

Meteor-docker expects to run with a docker daemon running on the same computer. If your docker socket is not standard (/var/run/docker.sock), you can specify it with the environment variable DOCKER_SOCKET.

**Comment by sachaudh** [comment]
I used the command 

    docker run -it --rm -p 3000:80 --link mongo:db -e "MONGO_URL=mongodb://db" -e "ROOT_URL=http://192.168.59.103:3000" --volume /var/run/docker.sock:/var/run/docker.sock --name dockerui dockerui

**Comment by sachaudh** [comment]
Also i couldn't find docker.sock in my /var/run/ folder. Is that why I can't access anything right now?
