### ISSUE TITLE
Building and running a docker image from the repo

### ISSUE THREAD

**Issue by sachaudh** [djedi23/meteor-docker#2]
So I made a docker image out of the git repo and ran it. I'm having a problem where it doesn't show the images I have or containers after I logged in.

![screen shot 2015-07-08 at 1 36 35 pm](https://cloud.githubusercontent.com/assets/4805485/8581581/95cac0c0-2576-11e5-9c59-aa67d71dd9ba.png)

If you check the bottom, you can see i'm not receiving any errors. I'm unsure why its not displaying anything.

**Comment by sachaudh** [comment]
Although it does say "Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?"

**Comment by sachaudh** [comment]
I'm trying to clone it on my Mac and try to build a docker image out of it to run. Doesn't seem to display anything. Wondering what i'm doing wrong.

**Comment by sachaudh** [comment]
I figured out the problem. I used the following commands 

```
docker run --name dtcmongodb -d mongo:2.4.12

docker run -it --rm -p 3000:80 --link dtcmongodb:dtcmongodb -e "MONGO_URL=mongodb://dtcmongodb" -e "ROOT_URL=http://192.168.59.103:3000" --volume /var/run/docker.sock:/var/run/docker.sock --name dockerui dockerui
```

where **dockerui** is my docker image built using the cloned repo, and **dtcmongodb** is the container for the mongodb database. Apparently if you use a different name for **dtcmongo** and do **--link mongo:mongo**, for example, then it messes up. Are you hardcoding anything for the database?

**Comment by sachaudh** [comment]
It might also be helpful to add to the README how to create an image and run it from the cloned repo

**Comment by sachaudh** [comment]
Also, I get this output when running the server. Where are you sending this error from, and why does it generate?

![screen shot 2015-07-09 at 9 56 19 am](https://cloud.githubusercontent.com/assets/4805485/8601426/dc8dc7f0-2620-11e5-9eb5-5cc47f7bee84.png)

**Comment by djedi23** [comment]
This error directly came from the docker api.
